FROM python:3.9
WORKDIR /app
COPY requirements.ui.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . ./
CMD ["streamlit", "run", "app/ui/ui.py", \
     "--server.port", "5000", \
     "--server.address", "0.0.0.0", \
     "--server.headless", "true"]
