version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8086:8000"
    volumes:
      - .:/app

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8080:5000"
    volumes:
      - .:/app

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: me
      MYSQL_PASSWORD: me
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["python", "app/api/action_worker.py"]
    depends_on:
      - rabbitmq
      - db

  processor:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["python", "app/api/summarize_worker.py"]
    depends_on:
      - rabbitmq
      - db
